matches:
- trigger: ":tari"
  replace: "dr. Putu Yuniadi Antari"
- trigger: ":ste"
  replace: "dr. Stephanie Darda Susilowati"
- trigger: ":ays"
  replace: "dr. Ayu Shinta Mahaputri"
- trigger: ":lar"
  replace: "dr. Ni Made Praba Laras Kinasih"
- trigger: ":rian"
  replace: "dr. I Made Rian Amerta Dananjaya"
- trigger: ":tiw"
  replace: "dr. Putu Satya Pratiwi"
- trigger: ":saty"
  replace: "dr. Putu Satya Prameswari"
- trigger: ":desa"
  replace: "dr. Desak Putu Rendang Indriyani "
- trigger: ":ard"
  replace: "dr. Sardono Widinugroho "
- trigger: ":dian"
  replace: "dr. I Gusti Ayu Dian Noviyani Sidiartha"
- trigger: ":car"
  replace: "dr. Carlson Kurniawan"
- trigger: ":vik"
  replace: "dr. A. A. Wulan Vikanaswari Adnyana"
- trigger: ":dan"
  replace: "dr. Daniel Kurniawan Sintoro"
- trigger: ":jev"
  replace: "dr. Jeven Reggie"
- trigger: ":bun"
  replace: "dr. Bunga Sukmapermata"
- trigger: ":and"
  replace: "dr. Gde Andi Dwipantara Tungga Parmita"
- trigger: ":joy"
  replace: "dr. Joy Aprianis Haning"
- trigger: ":gez"
  replace: "dr. Putu Geza Gajendra Wardana"
- trigger: ":okt"
  replace: "dr. Ida Ayu Okti Cahyani Putri"
- trigger: ":jul"
  replace: "dr. Ni Putu Julia Lindayani"
- trigger: ":dan"
  replace: "dr. Agung Danan Jaya"
- trigger: ":yad"
  replace: "dr. Suryadi Limardi"
- trigger: ":yut"
  replace: "dr. Made Yuliantari Dwi Astiti "
- trigger: ":may"
  replace: "dr. Mayland Margaretha Sunata"
- trigger: ":adit"
  replace: "dr. Kadek Adi Suryamulyawan "
- trigger: ":ano"
  replace: "dr. Ida Bagus Anom Dharma Putra"
- trigger: ":int"
  replace: "dr. Intan Astariani"
- trigger: ":dann"
  replace: "dr. Ida Bagus Gede Danny Ananta"
- trigger: ":dwi"
  replace: "dr. Made Dwitia Ayu Iswari"
- trigger: ":kar"
  replace: "dr. A. A. A. Karina Damayanti"
- trigger: ":ana"
  replace: "dr. Indriana Triastuti"
- trigger: ":yay"
  replace: "dr. Made Cynthia Mahardika P."
- trigger: ":ria"
  replace: "dr. Putu Ria Asprila Dewi"
- trigger: ":tas"
  replace: "dr. Tasya Gitaputri Pranoto"
- trigger: ":ew"
  replace: "dr. I Gusti Ayu Mahadewi"
- trigger: ":as"
  replace: "dr. Ni Kadek Risa Astria"
- trigger: ":el"
  replace: "dr. Ni Putu Ayu Elistya Ning Purwani"
- trigger: ":te"
  replace: "dr. Teo Wijaya"
- trigger: ":tars"
  replace: "dr. Kadek Dwi Tarsika"
- trigger: ":indi"
  replace: "dr. Ade Tsarina Indira"
- trigger: ":vic"
  replace: "dr. Vica Natalia Gonga"
- trigger: ":kri"
  replace: "dr. I Ketut Krisna Indrawan"
- trigger: ":ary"
  replace: "dr. Arya Krisna Manggala"
- trigger: ":gle"
  replace: "dr. Glen Lazarus"
- trigger: ":fan"
  replace: "dr. Steffany Maria Lainama"
- trigger: ":ire"
  replace: "dr. Irene Fenia"
- trigger: ":gun"
  replace: "dr. I Gusti Agung Gede Narayana"
- trigger: ":pet"
  replace: "dr. Peter Prayogo Hsieh"
- trigger: ":wil"
  replace: "dr. Putu Wiliska Wilasitha"
- trigger: ":bon"
  replace: "dr. Bonny Pabetting"
- trigger: ":yog"
  replace: "dr. I Gede Yogi Priyatna Biantara"
- trigger: ":adit"
  replace: "dr. Tio Aditya Djohar"
- trigger: ":ind"
  replace: "dr. Ni Putu Indah Kartika Putri"
- trigger: ":sar"
  replace: "dr. Putu Diah Saraswati Rahayu"
- trigger: ":ev"
  replace: "dr. Evan Matthew Putra"
- trigger: ":ol"
  replace: "dr. Veronica Olga Pasca Sari"
- trigger: ":del"
  replace: "dr. Della Sabrina Marta"
- trigger: ":nad"
  replace: "dr. Nadya Gratia Juliawan"
- trigger: ":cel"
  replace: "dr. Celine"
- trigger: ":fris"
  replace: "dr. Putu Fristy Armatheina"
- trigger: ":rer"
  replace: "dr. Sreshta Jaikumar Mukhi"
- trigger: ":erv"
  replace: "dr. Ervin Melcianto"
- trigger: ":enn"
  replace: "dr. Kadek Enny Pradnyaswari"
- trigger: ":pupu"
  replace: "dr. Luh Putu Arya Putri Ratnasari"
- trigger: ":did"
  replace: "dr. I Dewa Ayu Agung Diah Sutarini"
- trigger: ":put"
  replace: "dr. Anak Agung Puteri Indira Rajani"
- trigger: ":Dias"
  replace: "dr. Ni Luh Putu Diaswari Predani"
- trigger: ":mar"
  replace: "dr. Marissa Leviani Hadiyanto"
- trigger: ":fel"
  replace: "dr. Felicitas Anindya Utami"
- trigger: ":kh"
  replace: "dr. Khema Metta Wijaya"
- trigger: ":nin"
  replace: "dr. Made Nindya Prahasari Wismawan"
- trigger: ":fer"
  replace: "dr. Ferry Suganda Gozali"
- trigger: ":nan"
  replace: "dr. Nyoman Ananda Putri Prashanti"
- trigger: ":nia"
  replace: "dr. Nathania Thedra"
- trigger: ":am"
  replace: "dr. Luh Kadek Shastri Utami Wijayanti"
- trigger: ":jef"
  replace: "dr. Jefry"
- trigger: ":vin"
  replace: "dr. Dewa Ayu Viennita Verdyanti Suria"
- trigger: ":rei"
  replace: "dr. Reinildis Hildegardis Uruk Hane"
- trigger: ":jes"
  replace: "dr. Jessica Christina"
- trigger: ":ang"
  replace: "dr. Ni Putu Anggita Medyantari"
- trigger: ":indr"
  replace: "dr. I Gede Indradika Pratama Putra"
- trigger: ":jess"
  replace: "dr. Jesslyn Norberta"
- trigger: ":tita"
  replace: "dr. G. A. Amalindasari Prabayastita M."
- trigger: ":sara"
  replace: "dr. Nian Sarawarastri "
- trigger: ":gla"
  replace: "⁠dr. Ni Putu Gladys Arys Paramerta"
- trigger: ":her"
  replace: "dr. Herlince Wehelmina Amalo "
- trigger: ":reg"
  replace: "dr. Regina Suriadi  "
- trigger: ":nat"
  replace: "dr. Claudia Natasha Liman"
- trigger: ":jane"
  replace: "dr. Janet Tee"
- trigger: ":hen"
  replace: "dr. I Putu Hendri Aryadi"
- trigger: ":wang"
  replace: "dr. I Putu Satrya Indrawangsa  "
- trigger: ":stev"
  replace: "dr. Stevan Pagar Pardamean S."
- trigger: ":ant"
  replace: "dr. Anthony Tjajaindra"
- trigger: ":gang"
  replace: "dr. Gangga Devi Padma"
- trigger: ":pra"
  replace: "dr. Putu Agung Satvika Pradnyasari"
- trigger: ":ref"
  replace: "dr. Made Refika Widya Apsari Tangkas"
- trigger: ":wid"
  replace: "dr. Putu Wila Widiastuti"
- trigger: ":rut"
  replace: "dr. Ruthie Aviana"
- trigger: ":dess"
  replace: "dr. Dessy Natasha Ade Putri"
- trigger: ":dit"
  replace: "dr. Ni Putu Ditadiliyana Putri"
- trigger: ":rit"
  replace: "dr. Nyoman Titamarita Trisnawan"
- trigger: ":git"
  replace: "dr. Ni Made Gita Andariska"
- trigger: ":mah"
  replace: "dr. Putu Dharma Putri Mahastuti"
- trigger: ":yoga"
  replace: "dr. Ida Bagus Yoga Dwityatama"
- trigger: ":tris"
  replace: "dr. Ida Ayu Trisha Kundalini"