matches:
- trigger: ";tari"
  replace: "Putu Yuniadi Antari, MD"
- trigger: ";ste"
  replace: "Stephanie Darda Susilowati, MD"
- trigger: ";ays"
  replace: "Ayu Shinta Mahaputri, MD"
- trigger: ";lar"
  replace: "Ni Made Praba Laras Kinasih, MD"
- trigger: ";rian"
  replace: "I Made Rian Amerta Dananjaya, MD"
- trigger: ";tiw"
  replace: "Putu Satya Pratiwi, MD"
- trigger: ";saty"
  replace: "Putu Satya Prameswari, MD"
- trigger: ";desa"
  replace: "Desak Putu Rendang Indriyani, MD"
- trigger: ";ard"
  replace: "Sardono Widinugroho, MD"
- trigger: ";dian"
  replace: "I Gusti Ayu Dian Noviyani Sidiartha, MD"
- trigger: ";car"
  replace: "Carlson Kurniawan, MD"
- trigger: ";vik"
  replace: "A. A. Wulan Vikanaswari Adnyana, MD"
- trigger: ";dan"
  replace: "Daniel Kurniawan Sintoro, MD"
- trigger: ";jev"
  replace: "Jeven Reggie, MD"
- trigger: ";bun"
  replace: "Bunga Sukmapermata, MD"
- trigger: ";and"
  replace: "Gde Andi Dwipantara Tungga Parmita, MD"
- trigger: ";joy"
  replace: "Joy Aprianis Haning, MD"
- trigger: ";gez"
  replace: "Putu Geza Gajendra Wardana, MD"
- trigger: ";okt"
  replace: "Ida Ayu Okti Cahyani Putri, MD"
- trigger: ";jul"
  replace: "Ni Putu Julia Lindayani, MD"
- trigger: ";dan"
  replace: "Agung Danan Jaya, MD"
- trigger: ";yad"
  replace: "Suryadi Limardi, MD"
- trigger: ";yut"
  replace: "Made Yuliantari Dwi Astiti , MD"
- trigger: ";may"
  replace: "Mayland Margaretha Sunata, MD"
- trigger: ";adit"
  replace: "Kadek Adi Suryamulyawan , MD"
- trigger: ";ano"
  replace: "Ida Bagus Anom Dharma Putra, MD"
- trigger: ";int"
  replace: "Intan Astani, MD"
- trigger: ";dann"
  replace: "Ida Bagus Gede Danny Ananta, MD"
- trigger: ";dwi"
  replace: "Made Dwitia Ayu Iswari, MD"
- trigger: ";kar"
  replace: "A. A. A. Karina Damayanti, MD"
- trigger: ";ana"
  replace: "Indiana Triastuti, MD"
- trigger: ";yay"
  replace: "Made Cynthia Mahardika P., MD"
- trigger: ";ria as"
  replace: "Putu Ria Asprila Dewi, MD"
- trigger: ";tas"
  replace: "Tasya Gitaputri Pranoto, MD"
- trigger: ";ew"
  replace: "I Gusti Ayu Mahadewi, MD"
- trigger: ";astri"
  replace: "Ni Kadek Risa Astria, MD"
- trigger: ";el"
  replace: "Ni Putu Ayu Elistya Ning Purwani, MD"
- trigger: ";te"
  replace: "Teo Wijaya, MD"
- trigger: ";tars"
  replace: "Kadek Dwi Tarsika, MD"
- trigger: ";indi"
  replace: "Ade Tsarina Indira, MD"
- trigger: ";vic"
  replace: "Vica Natalia Gonga, MD"
- trigger: ";kri"
  replace: "I Ketut Krisna Indrawan, MD"
- trigger: ";ary"
  replace: "Arya Krisna Manggala, MD"
- trigger: ";gle"
  replace: "Glen Lazarus, MD"
- trigger: ";fan"
  replace: "Steffany Maria Lainama, MD"
- trigger: ";ire"
  replace: "Irene Fenia, MD"
- trigger: ";gun"
  replace: "I Gusti Agung Gede Narayana, MD"
- trigger: ";pet"
  replace: "Peter Prayogo Hsieh, MD"
- trigger: ";wil"
  replace: "Putu Wiliska Wilasitha, MD"
- trigger: ";bon"
  replace: "Bonny Pabetting, MD"
- trigger: ";yog"
  replace: "I Gede Yogi Priyatna Biantara, MD"
- trigger: ";adit"
  replace: "Tio Aditya Djohar, MD"
- trigger: ";ind"
  replace: "Ni Putu Indah Kartika Putri, MD"
- trigger: ";sar"
  replace: "Putu Diah Saraswati Rahayu, MD"
- trigger: ";ev"
  replace: "Evan Matthew Putra, MD"
- trigger: ";ol"
  replace: "Veronica Olga Pasca Sari, MD"
- trigger: ";del"
  replace: "Della Sabrina Marta, MD"
- trigger: ";nad"
  replace: "Nadya Gratia Juliawan, MD"
- trigger: ";cel"
  replace: "Celine, MD"
- trigger: ";fris"
  replace: "Putu Fristy Armatheina, MD"
- trigger: ";rer"
  replace: "Sreshta Jaikumar Mukhi, MD"
- trigger: ";erv"
  replace: "Ervin Melcianto, MD"
- trigger: ";enn"
  replace: "Kadek Enny Pradnyaswari, MD"
- trigger: ";pupu"
  replace: "Luh Putu Arya Putri Ratnasari, MD"
- trigger: ";did"
  replace: "I Dewa Ayu Agung Diah Sutarini, MD"
- trigger: ";put"
  replace: "Anak Agung Puteri Indira Rajani, MD"
- trigger: ";Dias"
  replace: "Ni Luh Putu Diaswari Predani, MD"
- trigger: ";mar"
  replace: "Marissa Leviani Hadiyanto, MD"
- trigger: ";fel"
  replace: "Felicitas Anindya Utami, MD"
- trigger: ";kh"
  replace: "Khema Metta Wijaya, MD"
- trigger: ";nin"
  replace: "Made Nindya Prahasari Wismawan, MD"
- trigger: ";fer"
  replace: "Ferry Suganda Gozali, MD"
- trigger: ";nan"
  replace: "Nyoman Ananda Putri Prashanti, MD"
- trigger: ";nia"
  replace: "Nathania Thedra, MD"
- trigger: ";am"
  replace: "Luh Kadek Shastri Utami Wijayanti, MD"
- trigger: ";jef"
  replace: "Jefry, MD"
- trigger: ";vin"
  replace: "Dewa Ayu Viennita Verdyanti Suria, MD"
- trigger: ";rei"
  replace: "Reinildis Hildegardis Uruk Hane, MD"
- trigger: ";jes"
  replace: "Jessica Christina, MD"
- trigger: ";ang"
  replace: "Ni Putu Anggita Medyantari, MD"
- trigger: ";indr"
  replace: "I Gede Indradika Pratama Putra, MD"
- trigger: ";jess"
  replace: "Jesslyn Norberta, MD"
- trigger: ";tita"
  replace: "G. A. Amalindasari Prabayastita M., MD"
- trigger: ";sara"
  replace: "Nian Sarawarastri, MD"
- trigger: ";gla"
  replace: " Ni Putu Gladys Arys Paramerta, MD"
- trigger: ";her"
  replace: "Herlince Wehelmina Amalo, MD"
- trigger: ";reg"
  replace: "Regina Suriadi, MD"
- trigger: ";nat"
  replace: "Claudia Natasha Liman, MD"
- trigger: ";jane"
  replace: "Janet Tee, MD"
- trigger: ";hen"
  replace: "I Putu Hendri Aryadi, MD"
- trigger: ";wang"
  replace: "I Putu Satrya Indrawangsa, MD"
- trigger: ";stev"
  replace: "Stevan Pagar Pardamean S., MD"
- trigger: ";ant"
  replace: "Anthony Tjajaindra, MD"
- trigger: ";gang"
  replace: "Gangga Devi Padma, MD"
- trigger: ";pra"
  replace: "Putu Agung Satvika Pradnyasari, MD"
- trigger: ";ref"
  replace: "Made Refika Widya Apsari Tangkas, MD"
- trigger: ";wid"
  replace: "Putu Wila Widiastuti, MD"
- trigger: ";rut"
  replace: "Ruthie Aviana, MD"
- trigger: ";dess"
  replace: "Dessy Natasha Ade Putri, MD"
- trigger: ";dit"
  replace: "Ni Putu Ditadiliyana Putri, MD"
- trigger: ";rit"
  replace: "Nyoman Titamarita Trisnawan, MD"
- trigger: ";git"
  replace: "Ni Made Gita Andariska, MD"
- trigger: ";mah"
  replace: "Putu Dharma Putri Mahastuti, MD"
- trigger: ";yoga"
  replace: "Ida Bagus Yoga Dwityatama, MD"
- trigger: ";tris"
  replace: "Ida Ayu Trisha Kundalini, MD"
- trigger: ":tari"
  replace: "dr. Putu Yuniadi Antari"
- trigger: ":ste"
  replace: "dr. Stephanie Darda Susilowati"
- trigger: ":ays"
  replace: "dr. Ayu Shinta Mahaputri"
- trigger: ":lar"
  replace: "dr. Ni Made Praba Laras Kinasih"
- trigger: ":rian"
  replace: "dr. I Made Rian Amerta Dananjaya"
- trigger: ":tiw"
  replace: "dr. Putu Satya Pratiwi"
- trigger: ":saty"
  replace: "dr. Putu Satya Prameswari"
- trigger: ":desa"
  replace: "dr. Desak Putu Rendang Indriyani"
- trigger: ":ard"
  replace: "dr. Sardono Widinugroho"
- trigger: ":dian"
  replace: "dr. I Gusti Ayu Dian Noviyani Sidiartha"
- trigger: ":car"
  replace: "dr. Carlson Kurniawan"
- trigger: ":vik"
  replace: "dr. A. A. Wulan Vikanaswari Adnyana"
- trigger: ":dan"
  replace: "dr. Daniel Kurniawan Sintoro"
- trigger: ":jev"
  replace: "dr. Jeven Reggie"
- trigger: ":bun"
  replace: "dr. Bunga Sukmapermata"
- trigger: ":and"
  replace: "dr. Gde Andi Dwipantara Tungga Parmita"
- trigger: ":joy"
  replace: "dr. Joy Aprianis Haning"
- trigger: ":gez"
  replace: "dr. Putu Geza Gajendra Wardana"
- trigger: ":okt"
  replace: "dr. Ida Ayu Okti Cahyani Putri"
- trigger: ":jul"
  replace: "dr. Ni Putu Julia Lindayani"
- trigger: ":dan"
  replace: "dr. Agung Danan Jaya"
- trigger: ":yad"
  replace: "dr. Suryadi Limardi"
- trigger: ":yut"
  replace: "dr. Made Yuliantari Dwi Astiti "
- trigger: ":may"
  replace: "dr. Mayland Margaretha Sunata"
- trigger: ":adit"
  replace: "dr. Kadek Adi Suryamulyawan "
- trigger: ":ano"
  replace: "dr. Ida Bagus Anom Dharma Putra"
- trigger: ":int"
  replace: "dr. Intan Astariani"
- trigger: ":dann"
  replace: "dr. Ida Bagus Gede Danny Ananta"
- trigger: ":dwi"
  replace: "dr. Made Dwitia Ayu Iswari"
- trigger: ":karina"
  replace: "dr. A. A. A. Karina Damayanti"
- trigger: ":ana"
  replace: "dr. Indriana Triastuti"
- trigger: ":yay"
  replace: "dr. Made Cynthia Mahardika P."
- trigger: ":riaaspri"
  replace: "dr. Putu Ria Asprila Dewi"
- trigger: ":tasya"
  replace: "dr. Tasya Gitaputri Pranoto"
- trigger: ":ewik"
  replace: "dr. I Gusti Ayu Mahadewi"
- trigger: ":astri"
  replace: "dr. Ni Kadek Risa Astria"
- trigger: ":elis"
  replace: "dr. Ni Putu Ayu Elistya Ning Purwani"
- trigger: ":teo"
  replace: "dr. Teo Wijaya"
- trigger: ":tars"
  replace: "dr. Kadek Dwi Tarsika"
- trigger: ":indi"
  replace: "dr. Ade Tsarina Indira"
- trigger: ":vica"
  replace: "dr. Vica Natalia Gonga"
- trigger: ":krisna"
  replace: "dr. I Ketut Krisna Indrawan"
- trigger: ":arya"
  replace: "dr. Arya Krisna Manggala"
- trigger: ":glen"
  replace: "dr. Glen Lazarus"
- trigger: ":fan"
  replace: "dr. Steffany Maria Lainama"
- trigger: ":ire"
  replace: "dr. Irene Fenia"
- trigger: ":gung de"
  replace: "dr. I Gusti Agung Gede Narayana"
- trigger: ":pet"
  replace: "dr. Peter Prayogo Hsieh"
- trigger: ":wila"
  replace: "dr. Putu Wiliska Wilasitha"
- trigger: ":bon"
  replace: "dr. Bonny Pabetting"
- trigger: ":yog"
  replace: "dr. I Gede Yogi Priyatna Biantara"
- trigger: ":adit"
  replace: "dr. Tio Aditya Djohar"
- trigger: ":indah"
  replace: "dr. Ni Putu Indah Kartika Putri"
- trigger: ":sar"
  replace: "dr. Putu Diah Saraswati Rahayu"
- trigger: ":ev"
  replace: "dr. Evan Matthew Putra"
- trigger: ":ol"
  replace: "dr. Veronica Olga Pasca Sari"
- trigger: ":del"
  replace: "dr. Della Sabrina Marta"
- trigger: ":nad"
  replace: "dr. Nadya Gratia Juliawan"
- trigger: ":cel"
  replace: "dr. Celine"
- trigger: ":fris"
  replace: "dr. Putu Fristy Armatheina"
- trigger: ":rer"
  replace: "dr. Sreshta Jaikumar Mukhi"
- trigger: ":erv"
  replace: "dr. Ervin Melcianto"
- trigger: ":enny"
  replace: "dr. Kadek Enny Pradnyaswari"
- trigger: ":pupu"
  replace: "dr. Luh Putu Arya Putri Ratnasari"
- trigger: ":did"
  replace: "dr. I Dewa Ayu Agung Diah Sutarini"
- trigger: ":put"
  replace: "dr. Anak Agung Puteri Indira Rajani"
- trigger: ":dias"
  replace: "dr. Ni Luh Putu Diaswari Predani"
- trigger: ":mar"
  replace: "dr. Marissa Leviani Hadiyanto"
- trigger: ":feli"
  replace: "dr. Felicitas Anindya Utami"
- trigger: ":khem"
  replace: "dr. Khema Metta Wijaya"
- trigger: ":nin"
  replace: "dr. Made Nindya Prahasari Wismawan"
- trigger: ":fer"
  replace: "dr. Ferry Suganda Gozali"
- trigger: ":nanda"
  replace: "dr. Nyoman Ananda Putri Prashanti"
- trigger: ":nia"
  replace: "dr. Nathania Thedra"
- trigger: ":ami"
  replace: "dr. Luh Kadek Shastri Utami Wijayanti"
- trigger: ":jef"
  replace: "dr. Jefry"
- trigger: ":vin"
  replace: "dr. Dewa Ayu Viennita Verdyanti Suria"
- trigger: ":rei"
  replace: "dr. Reinildis Hildegardis Uruk Hane"
- trigger: ":jes"
  replace: "dr. Jessica Christina"
- trigger: ":ang"
  replace: "dr. Ni Putu Anggita Medyantari"
- trigger: ":indr"
  replace: "dr. I Gede Indradika Pratama Putra"
- trigger: ":jess"
  replace: "dr. Jesslyn Norberta"
- trigger: ":tita"
  replace: "dr. G. A. Amalindasari Prabayastita M."
- trigger: ":sara"
  replace: "dr. Nian Sarawarastri"
- trigger: ":gla"
  replace: "dr. Ni Putu Gladys Arys Paramerta"
- trigger: ":her"
  replace: "dr. Herlince Wehelmina Amalo"
- trigger: ":reg"
  replace: "dr. Regina Suriadi"
- trigger: ":nat"
  replace: "dr. Claudia Natasha Liman"
- trigger: ":jane"
  replace: "dr. Janet Tee"
- trigger: ":hen"
  replace: "dr. I Putu Hendri Aryadi"
- trigger: ":wang"
  replace: "dr. I Putu Satrya Indrawangsa"
- trigger: ":stev"
  replace: "dr. Stevan Pagar Pardamean S."
- trigger: ":anton"
  replace: "dr. Anthony Tjajaindra"
- trigger: ":gangga"
  replace: "dr. Gangga Devi Padma"
- trigger: ":pradnya"
  replace: "dr. Putu Agung Satvika Pradnyasari"
- trigger: ":refi"
  replace: "dr. Made Refika Widya Apsari Tangkas"
- trigger: ":widia"
  replace: "dr. Putu Wila Widiastuti"
- trigger: ":rut"
  replace: "dr. Ruthie Aviana"
- trigger: ":dess"
  replace: "dr. Dessy Natasha Ade Putri"
- trigger: ":dita"
  replace: "dr. Ni Putu Ditadiliyana Putri"
- trigger: ":rita"
  replace: "dr. Nyoman Titamarita Trisnawan"
- trigger: ":gita"
  replace: "dr. Ni Made Gita Andariska"
- trigger: ":mah"
  replace: "dr. Putu Dharma Putri Mahastuti"
- trigger: ":yoga"
  replace: "dr. Ida Bagus Yoga Dwityatama"
- trigger: ":tris"
  replace: "dr. Ida Ayu Trisha Kundalini"
