matches:
- trigger: ";tari"
  replace: "Putu Yuniadi Antari, MD"
- trigger: ";ste"
  replace: "Stephanie Darda Susilowati, MD"
- trigger: ";ays"
  replace: "Ayu Shinta Mahaputri, MD"
- trigger: ";lar"
  replace: "Ni Made Praba Laras Kinasih, MD"
- trigger: ";rian"
  replace: "I Made Rian Amerta Dananjaya, MD"
- trigger: ";tiw"
  replace: "Putu Satya Pratiwi, MD"
- trigger: ";saty"
  replace: "Putu Satya Prameswari, MD"
- trigger: ";desa"
  replace: "Desak Putu Rendang Indriyani , MD"
- trigger: ";ard"
  replace: "Sardono Widinugroho , MD"
- trigger: ";dian"
  replace: "I Gusti Ayu Dian Noviyani Sidiartha, MD"
- trigger: ";car"
  replace: "Carlson Kurniawan, MD"
- trigger: ";vik"
  replace: "A. A. Wulan Vikanaswari Adnyana, MD"
- trigger: ";dan"
  replace: "Daniel Kurniawan Sintoro, MD"
- trigger: ";jev"
  replace: "Jeven Reggie, MD"
- trigger: ";bun"
  replace: "Bunga Sukmapermata, MD"
- trigger: ";and"
  replace: "Gde Andi Dwipantara Tungga Parmita, MD"
- trigger: ";joy"
  replace: "Joy Aprianis Haning, MD"
- trigger: ";gez"
  replace: "Putu Geza Gajendra Wardana, MD"
- trigger: ";okt"
  replace: "Ida Ayu Okti Cahyani Putri, MD"
- trigger: ";jul"
  replace: "Ni Putu Julia Lindayani, MD"
- trigger: ";dan"
  replace: "Agung Danan Jaya, MD"
- trigger: ";yad"
  replace: "Suryadi Limardi, MD"
- trigger: ";yut"
  replace: "Made Yuliantari Dwi Astiti , MD"
- trigger: ";may"
  replace: "Mayland Margaretha Sunata, MD"
- trigger: ";adit"
  replace: "Kadek Adi Suryamulyawan , MD"
- trigger: ";ano"
  replace: "Ida Bagus Anom Dharma Putra, MD"
- trigger: ";int"
  replace: "Intan Astariani, MD"
- trigger: ";dann"
  replace: "Ida Bagus Gede Danny Ananta, MD"
- trigger: ";dwi"
  replace: "Made Dwitia Ayu Iswari, MD"
- trigger: ";kar"
  replace: "A. A. A. Karina Damayanti, MD"
- trigger: ";ana"
  replace: "Indriana Triastuti, MD"
- trigger: ";yay"
  replace: "Made Cynthia Mahardika P., MD"
- trigger: ";ria"
  replace: "Putu Ria Asprila Dewi, MD"
- trigger: ";tas"
  replace: "Tasya Gitaputri Pranoto, MD"
- trigger: ";ew"
  replace: "I Gusti Ayu Mahadewi, MD"
- trigger: ";as"
  replace: "Ni Kadek Risa Astria, MD"
- trigger: ";el"
  replace: "Ni Putu Ayu Elistya Ning Purwani, MD"
- trigger: ";te"
  replace: "Teo Wijaya, MD"
- trigger: ";tars"
  replace: "Kadek Dwi Tarsika, MD"
- trigger: ";indi"
  replace: "Ade Tsarina Indira, MD"
- trigger: ";vic"
  replace: "Vica Natalia Gonga, MD"
- trigger: ";kri"
  replace: "I Ketut Krisna Indrawan, MD"
- trigger: ";ary"
  replace: "Arya Krisna Manggala, MD"
- trigger: ";gle"
  replace: "Glen Lazarus, MD"
- trigger: ";fan"
  replace: "Steffany Maria Lainama, MD"
- trigger: ";ire"
  replace: "Irene Fenia, MD"
- trigger: ";gun"
  replace: "I Gusti Agung Gede Narayana, MD"
- trigger: ";pet"
  replace: "Peter Prayogo Hsieh, MD"
- trigger: ";wil"
  replace: "Putu Wiliska Wilasitha, MD"
- trigger: ";bon"
  replace: "Bonny Pabetting, MD"
- trigger: ";yog"
  replace: "I Gede Yogi Priyatna Biantara, MD"
- trigger: ";adit"
  replace: "Tio Aditya Djohar, MD"
- trigger: ";ind"
  replace: "Ni Putu Indah Kartika Putri, MD"
- trigger: ";sar"
  replace: "Putu Diah Saraswati Rahayu, MD"
- trigger: ";ev"
  replace: "Evan Matthew Putra, MD"
- trigger: ";ol"
  replace: "Veronica Olga Pasca Sari, MD"
- trigger: ";del"
  replace: "Della Sabrina Marta, MD"
- trigger: ";nad"
  replace: "Nadya Gratia Juliawan, MD"
- trigger: ";cel"
  replace: "Celine, MD"
- trigger: ";fris"
  replace: "Putu Fristy Armatheina, MD"
- trigger: ";rer"
  replace: "Sreshta Jaikumar Mukhi, MD"
- trigger: ";erv"
  replace: "Ervin Melcianto, MD"
- trigger: ";enn"
  replace: "Kadek Enny Pradnyaswari, MD"
- trigger: ";pupu"
  replace: "Luh Putu Arya Putri Ratnasari, MD"
- trigger: ";did"
  replace: "I Dewa Ayu Agung Diah Sutarini, MD"
- trigger: ";put"
  replace: "Anak Agung Puteri Indira Rajani, MD"
- trigger: ";Dias"
  replace: "Ni Luh Putu Diaswari Predani, MD"
- trigger: ";mar"
  replace: "Marissa Leviani Hadiyanto, MD"
- trigger: ";fel"
  replace: "Felicitas Anindya Utami, MD"
- trigger: ";kh"
  replace: "Khema Metta Wijaya, MD"
- trigger: ";nin"
  replace: "Made Nindya Prahasari Wismawan, MD"
- trigger: ";fer"
  replace: "Ferry Suganda Gozali, MD"
- trigger: ";nan"
  replace: "Nyoman Ananda Putri Prashanti, MD"
- trigger: ";nia"
  replace: "Nathania Thedra, MD"
- trigger: ";am"
  replace: "Luh Kadek Shastri Utami Wijayanti, MD"
- trigger: ";jef"
  replace: "Jefry, MD"
- trigger: ";vin"
  replace: "Dewa Ayu Viennita Verdyanti Suria, MD"
- trigger: ";rei"
  replace: "Reinildis Hildegardis Uruk Hane, MD"
- trigger: ";jes"
  replace: "Jessica Christina, MD"
- trigger: ";ang"
  replace: "Ni Putu Anggita Medyantari, MD"
- trigger: ";indr"
  replace: "I Gede Indradika Pratama Putra, MD"
- trigger: ";jess"
  replace: "Jesslyn Norberta, MD"
- trigger: ";tita"
  replace: "G. A. Amalindasari Prabayastita M., MD"
- trigger: ";sara"
  replace: "Nian Sarawarastri , MD"
- trigger: ";gla"
  replace: " Ni Putu Gladys Arys Paramerta, MD"
- trigger: ";her"
  replace: "Herlince Wehelmina Amalo , MD"
- trigger: ";reg"
  replace: "Regina Suriadi  , MD"
- trigger: ";nat"
  replace: "Claudia Natasha Liman, MD"
- trigger: ";jane"
  replace: "Janet Tee, MD"
- trigger: ";hen"
  replace: "I Putu Hendri Aryadi, MD"
- trigger: ";wang"
  replace: "I Putu Satrya Indrawangsa  , MD"
- trigger: ";stev"
  replace: "Stevan Pagar Pardamean S., MD"
- trigger: ";ant"
  replace: "Anthony Tjajaindra, MD"
- trigger: ";gang"
  replace: "Gangga Devi Padma, MD"
- trigger: ";pra"
  replace: "Putu Agung Satvika Pradnyasari, MD"
- trigger: ";ref"
  replace: "Made Refika Widya Apsari Tangkas, MD"
- trigger: ";wid"
  replace: "Putu Wila Widiastuti, MD"
- trigger: ";rut"
  replace: "Ruthie Aviana, MD"
- trigger: ";dess"
  replace: "Dessy Natasha Ade Putri, MD"
- trigger: ";dit"
  replace: "Ni Putu Ditadiliyana Putri, MD"
- trigger: ";rit"
  replace: "Nyoman Titamarita Trisnawan, MD"
- trigger: ";git"
  replace: "Ni Made Gita Andariska, MD"
- trigger: ";mah"
  replace: "Putu Dharma Putri Mahastuti, MD"
- trigger: ";yoga"
  replace: "Ida Bagus Yoga Dwityatama, MD"
- trigger: ";tris"
  replace: "Ida Ayu Trisha Kundalini, MD"