matches:
- trigger: ";profhen"
  replace: "Prof. dr. Hendra Santoso, Sp.A(K)"
- trigger: ";profsuc"
  replace: "Prof.dr. Soetjiningsih, Sp.A(K)"
- trigger: ";dk"
  replace: "Ketut Dewi Kumara Wati, MD, PAED, Consultant, PhD"
- trigger: ";siadi"
  replace: "Ni Putu Siadi Purniti, MD, PAED, Consultant, PhD"
- trigger: ";karda"
  replace: "I Made Kardana, MD, PAED, Consultant, PhD"
- trigger: ";bikin"
  replace: "I Wayan Bikin Suryawan, MD, PAED, Consultant, PhD"
- trigger: ";lanang"
  replace: "I Gusti Lanang Sidiartha, MD, PAED, Consultant, PhD"
- trigger: ";suba"
  replace: "Ida Bagus Subanada, MD, PAED, Consultant, PhD"
- trigger: ";trisna"
  replace: "I Gusti Ayu Trisna Windiani, MD, PAED, Consultant, PhD"
- trigger: ";swb"
  replace: "I G. N. Made Suwarba, MD, PAED, Consultant, PhD"
- trigger: ";kary"
  replace: "I Putu Gede Karyana, MD, PAED, Consultant, PhD"
- trigger: ";supar"
  replace: "Ida Bagus Gede Suparyatha, MD, PAED, Consultant"
- trigger: ";arim"
  replace: "I Made Arimbawa, MD, PAED, Consultant, PhD"
- trigger: ";dhar"
  replace: "I Wayan Dharma Artana, MD, PAED, Consultant"
- trigger: ";eka"
  replace: "Eka Gunawijaya, MD, PAED, Consultant"
- trigger: ";ka"
  replace: "Ketut Ariawati, MD, PAED, Consultant, PhD"
- trigger: ";san"
  replace: "I G.N. Sanjaya Putra, MD, PAED, Consultant"
- trigger: ";dl"
  replace: "I Made Gede Dwi Lingga Utama, MD, PAED, Consultant, PhD"
- trigger: ";nila"
  replace: "Gusti Ayu Putu Nilawati, MD, PAED, Consultant, MARS"
- trigger: ";ds"
  replace: "Dewi Sutriani Mahalini, MD, PAED, PhD"
- trigger: ";wid"
  replace: "A. A. N. K. P. Widnyana, , MD, PAED, Consultant"
- trigger: ";juna"
  replace: "Putu Junara Putra, MD, PAED, Consultant"
- trigger: ";dyah"
  replace: "Dyah Kanya Wati, MD, PAED, Consultant, PhD"
- trigger: ";budi"
  replace: "I Nyoman Budi Hartawan, MD, M.Sc., PAED, Consultant, PhD"
- trigger: ";ayu"
  replace: "I G. A. P. Eka Pratiwi, MD, M.Kes, PAED, Consultant, PhD"
- trigger: ";sug"
  replace: "I G. A. N. Sugitha Adnyana, MD, PAED, Consultant"
- trigger: ";gus"
  replace: "dr. I Wayan Gustawan, MD, M.Sc., PAED, Consultant"
- trigger: ";rin"
  replace: "dr. Ayu Setyorini, MD, M. M., M.Sc., PAED, Consultant"
- trigger: ";wit"
  replace: "Komang Ayu Witarini, MD, PAED, Consultant"
- trigger: ";ven"
  replace: "Ni Putu Veny Kartika Yanti, MD, M.Sc.,PAED, Consultant, PhD"
- trigger: ";met"
  replace: "Ni Nyoman Metriani Nesa, MD, M.Sc., PAED, Consultant"
- trigger: ";suk"
  replace: "Made Sukmawati, MD, PAED, Consultant"
- trigger: ";ram"
  replace: "Ida Bagus Ramajaya Sutawan, MD, M.Biomed, PAED, Consultant"
- trigger: ";vina"
  replace: "Putu Mas Vina Paramitha, MD, M.Biomed, PAED"
- trigger: ";dy"
  replace: "I Made Darma Yuda, MD, M.Biomed, PAED"
- trigger: ";prat"
  replace: "Ni Luh Sukma Pratiwi Murti, MD, M.Biomed, PAED"
- trigger: ";krish"
  replace: "Bagus Ngurah Mahakrishna, MD, M.Biomed, PAED"
- trigger: ";yan"
  replace: "Kadek Ayu Yani Lastariana, MD, M.Biomed, PAED"
- trigger: ";apsa"
  replace: "Ni Luh Sri Apsari, MD, M.Biomed, PAED"
- trigger: ";upen"
  replace: "Wega Upendra Sindhughosa, MD, M.Biomed, PAED"
- trigger: ";yull"
  replace: "Made Yullyantara Saputra, MD, PAED"
- trigger: ";sis"
  replace: "Siska Permanasari Sinardja, MD, PAED"
- trigger: ";karm"
  replace: "I Made Karma Setiyawan, MD, PAED"
- trigger: ":profhen"
  replace: "Prof. dr. Hendra Santoso, Sp.A(K)"
- trigger: ":profsuc"
  replace: "Prof.dr. Soetjiningsih, Sp.A(K)"
- trigger: ":dk"
  replace: "Dr. dr. Ketut Dewi Kumara Wati, Sp.A(K)"
- trigger: ":siadi"
  replace: "Dr. dr. Ni Putu Siadi Purniti, Sp.A(K)"
- trigger: ":karda"
  replace: "Dr. dr. I Made Kardana, Sp.A(K)"
- trigger: ":bikin"
  replace: "Dr. dr. Wayan Bikin Suryawan, Sp.A(K)"
- trigger: ":lanang"
  replace: "Dr. dr. I Gusti Lanang Sidiartha, Sp.A(K)"
- trigger: ":suba"
  replace: "Dr. dr. Ida Bagus Subanada, Sp.A(K)"
- trigger: ":trisna"
  replace: "Dr. dr. I Gusti Ayu Trisna Windiani, Sp.A(K)"
- trigger: ":swb"
  replace: "Dr. dr. I G. N. Made Suwarba, Sp.A(K)"
- trigger: ":kary"
  replace: "Dr. dr. I Putu Gede Karyana, Sp.A(K)"
- trigger: ":supar"
  replace: "dr. Ida Bagus Gede Suparyatha, Sp.A(K)"
- trigger: ":arim"
  replace: "Dr. dr. I Made Arimbawa, Sp.A(K)"
- trigger: ":dhar"
  replace: "dr. I Wayan Dharma Artana, Sp.A(K)"
- trigger: ":eka"
  replace: "dr. Eka Gunawijaya, Sp.A(K)"
- trigger: ":ka"
  replace: "Dr. dr. Ketut Ariawati, Sp.A(K)"
- trigger: ":san"
  replace: "dr. I G.N. Sanjaya Putra, Sp.A(K)"
- trigger: ":dl"
  replace: "Dr. dr. I Made Gede Dwi Lingga Utama, Sp.A(K)"
- trigger: ":nila"
  replace: "dr. Gusti Ayu Putu Nilawati, Sp.A(K), MARS"
- trigger: ":ds"
  replace: "Dr. dr. Dewi Sutriani Mahalini, Sp.A"
- trigger: ":wid"
  replace: "dr. A. A. N. K. P. Widnyana, Sp.A(K)"
- trigger: ":juna"
  replace: "dr. Putu Junara Putra, Sp.A(K)"
- trigger: ":dyah"
  replace: "Dr. dr. Dyah Kanya Wati, Sp.A(K)"
- trigger: ":budi"
  replace: "Dr. dr. I Nyoman Budi Hartawan, M.Sc., Sp.A(K)"
- trigger: ":ayu"
  replace: "Dr. dr. I G. A. P. Eka Pratiwi, M.Kes., Sp.A(K)"
- trigger: ":sug"
  replace: "dr. I G. A. N. Sugitha Adnyana, Sp.A(K)"
- trigger: ":gus"
  replace: "dr. I Wayan Gustawan, M.Sc., Sp.A(K)"
- trigger: ":rin"
  replace: "dr. Ayu Setyorini M. M., M.Sc., Sp.A(K)"
- trigger: ":wit"
  replace: "dr. Komang Ayu Witarini, Sp.A(K)"
- trigger: ":ven"
  replace: "Dr. dr. Ni Putu Veny Kartika Yanti, M.Sc., Sp.A(K)"
- trigger: ":met"
  replace: "dr. Ni Nyoman Metriani Nesa, M.Sc., Sp.A(K)"
- trigger: ":suk"
  replace: "dr. Made Sukmawati, Sp.A(K)"
- trigger: ":ram"
  replace: "dr. I. B. Ramajaya S., M. Biomed, Sp.A(K)"
- trigger: ":vina"
  replace: "dr. Putu Mas Vina Paramitha, M.Biomed, Sp.A"
- trigger: ":dy"
  replace: "dr. I Made Darma Yuda, M.Biomed, Sp.A"
- trigger: ":prat"
  replace: "dr. Ni Luh Sukma Pratiwi Murti, M. Biomed, Sp.A"
- trigger: ":krish"
  replace: "dr. Bagus Ngurah Mahakrishna, M. Biomed, Sp.A"
- trigger: ":yan"
  replace: "dr. Kadek Ayu Yani Lastariana, M. Biomed, Sp.A"
- trigger: ":apsa"
  replace: "dr. Ni Luh Sri Apsari, M.Biomed., Sp.A"
- trigger: ":upen"
  replace: "dr. Wega Upendra Sindhughosa, M.Biomed, Sp.A"
- trigger: ":yull"
  replace: "dr. Made Yullyantara Saputra, Sp.A"
- trigger: ":sis"
  replace: "dr. Siska Permanasari Sinardja Sp.A"
- trigger: ":karm"
  replace: "dr. I Made Karma Setiyawan, Sp.A"