matches:
- trigger: ";profhen"
  replace: "Prof. dr. Hendra Santoso, Sp.A(K)"
- trigger: ";profsuc"
  replace: "Prof.dr. Soetjiningsih, Sp.A(K)"
- trigger: ";dk"
  replace: "Ketut Dewi Kumara Wati, MD, PAED, Consultant, PhD"
- trigger: ";siadi"
  replace: "Ni Putu Siadi Purniti, MD, PAED, Consultant, PhD"
- trigger: ";karda"
  replace: "I Made Kardana, MD, PAED, Consultant, PhD"
- trigger: ";bikin"
  replace: "I Wayan Bikin Suryawan, MD, PAED, Consultant, PhD"
- trigger: ";lanang"
  replace: "I Gusti Lanang Sidiartha, MD, PAED, Consultant, PhD"
- trigger: ";suba"
  replace: "Ida Bagus Subanada, MD, PAED, Consultant, PhD"
- trigger: ";trisna"
  replace: "I Gusti Ayu Trisna Windiani, MD, PAED, Consultant, PhD"
- trigger: ";swb"
  replace: "I G. N. Made Suwarba, MD, PAED, Consultant, PhD"
- trigger: ";karyana"
  replace: "I Putu Gede Karyana, MD, PAED, Consultant, PhD"
- trigger: ";supar"
  replace: "Ida Bagus Gede Suparyatha, MD, PAED, Consultant"
- trigger: ";arim"
  replace: "I Made Arimbawa, MD, PAED, Consultant, PhD"
- trigger: ";dhar"
  replace: "I Wayan Dharma Artana, MD, PAED, Consultant"
- trigger: ";ekagw"
  replace: "Eka Gunawijaya, MD, PAED, Consultant"
- trigger: ";ketut"
  replace: "Ketut Ariawati, MD, PAED, Consultant, PhD"
- trigger: ";san"
  replace: "I G.N. Sanjaya Putra, MD, PAED, Consultant"
- trigger: ";dl"
  replace: "I Made Gede Dwi Lingga Utama, MD, PAED, Consultant, PhD"
- trigger: ";nila"
  replace: "Gusti Ayu Putu Nilawati, MD, PAED, Consultant, MARS"
- trigger: ";ds"
  replace: "Dewi Sutriani Mahalini, MD, PAED, PhD"
- trigger: ";widnyana"
  replace: "A. A. N. K. P. Widnyana, , MD, PAED, Consultant"
- trigger: ";juna"
  replace: "Putu Junara Putra, MD, PAED, Consultant"
- trigger: ";dyah"
  replace: "Dyah Kanya Wati, MD, PAED, Consultant, PhD"
- trigger: ";budi"
  replace: "I Nyoman Budi Hartawan, MD, M.Sc., PAED, Consultant, PhD"
- trigger: ";ayueka"
  replace: "I G. A. P. Eka Pratiwi, MD, M.Kes, PAED, Consultant, PhD"
- trigger: ";sugitha"
  replace: "I G. A. N. Sugitha Adnyana, MD, PAED, Consultant"
- trigger: ";gustawan"
  replace: "dr. I Wayan Gustawan, MD, M.Sc., PAED, Consultant"
- trigger: ";ririn"
  replace: "dr. Ayu Setyorini, MD, M. M., M.Sc., PAED, Consultant"
- trigger: ";witarini"
  replace: "Komang Ayu Witarini, MD, PAED, Consultant"
- trigger: ";veny"
  replace: "Ni Putu Veny Kartika Yanti, MD, M.Sc.,PAED, Consultant, PhD"
- trigger: ";metri"
  replace: "Ni Nyoman Metriani Nesa, MD, M.Sc., PAED, Consultant"
- trigger: ";sukmawati"
  replace: "Made Sukmawati, MD, PAED, Consultant"
- trigger: ";rama"
  replace: "Ida Bagus Ramajaya Sutawan, MD, M.Biomed, PAED, Consultant"
- trigger: ";vina"
  replace: "Putu Mas Vina Paramitha, MD, M.Biomed, PAED"
- trigger: ";darmayuda"
  replace: "I Made Darma Yuda, MD, M.Biomed, PAED"
- trigger: ";sukmaprat"
  replace: "Ni Luh Sukma Pratiwi Murti, MD, M.Biomed, PAED"
- trigger: ";mahakris"
  replace: "Bagus Ngurah Mahakrishna, MD, M.Biomed, PAED"
- trigger: ";yani"
  replace: "Kadek Ayu Yani Lastariana, MD, M.Biomed, PAED"
- trigger: ";apsari"
  replace: "Ni Luh Sri Apsari, MD, M.Biomed, PAED"
- trigger: ";wega"
  replace: "Wega Upendra Sindhughosa, MD, M.Biomed, PAED"
- trigger: ";yull"
  replace: "Made Yullyantara Saputra, MD, PAED"
- trigger: ";siska"
  replace: "Siska Permanasari Sinardja, MD, PAED"
- trigger: ";karma"
  replace: "I Made Karma Setiyawan, MD, PAED"
