matches:
- trigger: ";profhen"
  replace: "Prof. dr. Hendra Santoso, Sp.A(K)"
- trigger: ";profsuc"
  replace: "Prof.dr. Soetjiningsih, Sp.A(K)"
- trigger: ";dk"
  replace: "Ketut Dewi Kumara Wati, MD, PAED, Consultant, PhD"
- trigger: ";siadi"
  replace: "Ni Putu Siadi Purniti, MD, PAED, Consultant, PhD"
- trigger: ";karda"
  replace: "I Made Kardana, MD, PAED, Consultant, PhD"
- trigger: ";bikin"
  replace: "I Wayan Bikin Suryawan, MD, PAED, Consultant, PhD"
- trigger: ";lanang"
  replace: "I Gusti Lanang Sidiartha, MD, PAED, Consultant, PhD"
- trigger: ";suba"
  replace: "Ida Bagus Subanada, MD, PAED, Consultant, PhD"
- trigger: ";trisna"
  replace: "I Gusti Ayu Trisna Windiani, MD, PAED, Consultant, PhD"
- trigger: ";swb"
  replace: "I G. N. Made Suwarba, MD, PAED, Consultant, PhD"
- trigger: ";karyana"
  replace: "I Putu Gede Karyana, MD, PAED, Consultant, PhD"
- trigger: ";supar"
  replace: "Ida Bagus Gede Suparyatha, MD, PAED, Consultant"
- trigger: ";arim"
  replace: "I Made Arimbawa, MD, PAED, Consultant, PhD"
- trigger: ";dhar"
  replace: "I Wayan Dharma Artana, MD, PAED, Consultant"
- trigger: ";ekagw"
  replace: "Eka Gunawijaya, MD, PAED, Consultant"
- trigger: ";ketut"
  replace: "Ketut Ariawati, MD, PAED, Consultant, PhD"
- trigger: ";san"
  replace: "I G.N. Sanjaya Putra, MD, PAED, Consultant"
- trigger: ";dl"
  replace: "I Made Gede Dwi Lingga Utama, MD, PAED, Consultant, PhD"
- trigger: ";nila"
  replace: "Gusti Ayu Putu Nilawati, MD, PAED, Consultant, MARS"
- trigger: ";ds"
  replace: "Dewi Sutriani Mahalini, MD, PAED, PhD"
- trigger: ";widnyana"
  replace: "A. A. N. K. P. Widnyana, , MD, PAED, Consultant"
- trigger: ";juna"
  replace: "Putu Junara Putra, MD, PAED, Consultant"
- trigger: ";dyah"
  replace: "Dyah Kanya Wati, MD, PAED, Consultant, PhD"
- trigger: ";budi"
  replace: "I Nyoman Budi Hartawan, MD, M.Sc., PAED, Consultant, PhD"
- trigger: ";ayueka"
  replace: "I G. A. P. Eka Pratiwi, MD, M.Kes, PAED, Consultant, PhD"
- trigger: ";sugitha"
  replace: "I G. A. N. Sugitha Adnyana, MD, PAED, Consultant"
- trigger: ";gustawan"
  replace: "dr. I Wayan Gustawan, MD, M.Sc., PAED, Consultant"
- trigger: ";ririn"
  replace: "dr. Ayu Setyorini, MD, M. M., M.Sc., PAED, Consultant"
- trigger: ";witarini"
  replace: "Komang Ayu Witarini, MD, PAED, Consultant"
- trigger: ";veny"
  replace: "Ni Putu Veny Kartika Yanti, MD, M.Sc.,PAED, Consultant, PhD"
- trigger: ";metri"
  replace: "Ni Nyoman Metriani Nesa, MD, M.Sc., PAED, Consultant"
- trigger: ";sukmawati"
  replace: "Made Sukmawati, MD, PAED, Consultant"
- trigger: ";rama"
  replace: "Ida Bagus Ramajaya Sutawan, MD, M.Biomed, PAED, Consultant"
- trigger: ";vina"
  replace: "Putu Mas Vina Paramitha, MD, M.Biomed, PAED"
- trigger: ";darmayuda"
  replace: "I Made Darma Yuda, MD, M.Biomed, PAED"
- trigger: ";sukmaprat"
  replace: "Ni Luh Sukma Pratiwi Murti, MD, M.Biomed, PAED"
- trigger: ";mahakris"
  replace: "Bagus Ngurah Mahakrishna, MD, M.Biomed, PAED"
- trigger: ";yani"
  replace: "Kadek Ayu Yani Lastariana, MD, M.Biomed, PAED"
- trigger: ";apsari"
  replace: "Ni Luh Sri Apsari, MD, M.Biomed, PAED"
- trigger: ";wega"
  replace: "Wega Upendra Sindhughosa, MD, M.Biomed, PAED"
- trigger: ";yull"
  replace: "Made Yullyantara Saputra, MD, PAED"
- trigger: ";siska"
  replace: "Siska Permanasari Sinardja, MD, PAED"
- trigger: ";karma"
  replace: "I Made Karma Setiyawan, MD, PAED"
- trigger: ":profhen"
  replace: "Prof. dr. Hendra Santoso, Sp.A(K)"
- trigger: ":profsuc"
  replace: "Prof.dr. Soetjiningsih, Sp.A(K)"
- trigger: ":dk"
  replace: "Dr. dr. Ketut Dewi Kumara Wati, Sp.A(K)"
- trigger: ":siadi"
  replace: "Dr. dr. Ni Putu Siadi Purniti, Sp.A(K)"
- trigger: ":karda"
  replace: "Dr. dr. I Made Kardana, Sp.A(K)"
- trigger: ":bikin"
  replace: "Dr. dr. Wayan Bikin Suryawan, Sp.A(K)"
- trigger: ":lanang"
  replace: "Dr. dr. I Gusti Lanang Sidiartha, Sp.A(K)"
- trigger: ":suba"
  replace: "Dr. dr. Ida Bagus Subanada, Sp.A(K)"
- trigger: ":trisna"
  replace: "Dr. dr. I Gusti Ayu Trisna Windiani, Sp.A(K)"
- trigger: ":swb"
  replace: "Dr. dr. I G. N. Made Suwarba, Sp.A(K)"
- trigger: ":karyana"
  replace: "Dr. dr. I Putu Gede Karyana, Sp.A(K)"
- trigger: ":supar"
  replace: "dr. Ida Bagus Gede Suparyatha, Sp.A(K)"
- trigger: ":arim"
  replace: "Dr. dr. I Made Arimbawa, Sp.A(K)"
- trigger: ":dharma"
  replace: "dr. I Wayan Dharma Artana, Sp.A(K)"
- trigger: ":ekagw"
  replace: "dr. Eka Gunawijaya, Sp.A(K)"
- trigger: ":ketut"
  replace: "Dr. dr. Ketut Ariawati, Sp.A(K)"
- trigger: ":san"
  replace: "dr. I G.N. Sanjaya Putra, Sp.A(K)"
- trigger: ":dl"
  replace: "Dr. dr. I Made Gede Dwi Lingga Utama, Sp.A(K)"
- trigger: ":nila"
  replace: "dr. Gusti Ayu Putu Nilawati, Sp.A(K), MARS"
- trigger: ":ds"
  replace: "Dr. dr. Dewi Sutriani Mahalini, Sp.A"
- trigger: ":widnyana"
  replace: "dr. A. A. N. K. P. Widnyana, Sp.A(K)"
- trigger: ":juna"
  replace: "dr. Putu Junara Putra, Sp.A(K)"
- trigger: ":dyah"
  replace: "Dr. dr. Dyah Kanya Wati, Sp.A(K)"
- trigger: ":budi"
  replace: "Dr. dr. I Nyoman Budi Hartawan, M.Sc., Sp.A(K)"
- trigger: ":ayueka"
  replace: "Dr. dr. I G. A. P. Eka Pratiwi, M.Kes., Sp.A(K)"
- trigger: ":sugitha"
  replace: "dr. I G. A. N. Sugitha Adnyana, Sp.A(K)"
- trigger: ":gustawan"
  replace: "dr. I Wayan Gustawan, M.Sc., Sp.A(K)"
- trigger: ":ririn"
  replace: "dr. Ayu Setyorini M. M., M.Sc., Sp.A(K)"
- trigger: ":witarini"
  replace: "dr. Komang Ayu Witarini, Sp.A(K)"
- trigger: ":veny"
  replace: "Dr. dr. Ni Putu Veny Kartika Yanti, M.Sc., Sp.A(K)"
- trigger: ":metri"
  replace: "dr. Ni Nyoman Metriani Nesa, M.Sc., Sp.A(K)"
- trigger: ":sukmawati"
  replace: "dr. Made Sukmawati, Sp.A(K)"
- trigger: ":rama"
  replace: "dr. I. B. Ramajaya S., M. Biomed, Sp.A(K)"
- trigger: ":vina"
  replace: "dr. Putu Mas Vina Paramitha, M.Biomed, Sp.A"
- trigger: ":darmayuda"
  replace: "dr. I Made Darma Yuda, M.Biomed, Sp.A"
- trigger: ":sukmapratiwi"
  replace: "dr. Ni Luh Sukma Pratiwi Murti, M. Biomed, Sp.A"
- trigger: ":mahakris"
  replace: "dr. Bagus Ngurah Mahakrishna, M. Biomed, Sp.A"
- trigger: ":yani"
  replace: "dr. Kadek Ayu Yani Lastariana, M. Biomed, Sp.A"
- trigger: ":apsari"
  replace: "dr. Ni Luh Sri Apsari, M.Biomed., Sp.A"
- trigger: ":wega"
  replace: "dr. Wega Upendra Sindhughosa, M.Biomed, Sp.A"
- trigger: ":yull"
  replace: "dr. Made Yullyantara Saputra, Sp.A"
- trigger: ":siska"
  replace: "dr. Siska Permanasari Sinardja Sp.A"
- trigger: ":karma"
  replace: "dr. I Made Karma Setiyawan, Sp.A"
