matches:
- trigger: ";profhen"
  replace: "Prof. dr. Hendra Santoso, Sp.A(K)"
- trigger: ";profsuc"
  replace: "Prof.dr. Soetjiningsih, Sp.A(K)"
- trigger: ";dk"
  replace: "Ketut Dewi Kumara Wati, MD, PAED, Consultant​, PhD"
- trigger: ";siadi"
  replace: "Ni Putu Siadi Purniti, MD, PAED, Consultant​, PhD"
- trigger: ";karda"
  replace: "I Made Kardana, MD, PAED, Consultant​, PhD"
- trigger: ";bikin"
  replace: "I Wayan Bikin Suryawan, MD, PAED, Consultant​, PhD"
- trigger: ";lanang"
  replace: "I Gusti Lanang Sidiartha, MD, PAED, Consultant​, PhD"
- trigger: ";suba"
  replace: "Ida Bagus Subanada, MD, PAED, Consultant​, PhD"
- trigger: ";trisna"
  replace: "I Gusti Ayu Trisna Windiani, MD, PAED, Consultant​, PhD"
- trigger: ";swb"
  replace: "I G. N. Made Suwarba, MD, PAED, Consultant​, PhD"
- trigger: ";kary"
  replace: "I Putu Gede Karyana, MD, PAED, Consultant​, PhD"
- trigger: ";supar"
  replace: "Ida Bagus Gede Suparyatha, MD, PAED, Consultant​"
- trigger: ";arim"
  replace: "I Made Arimbawa, MD, PAED, Consultant​, PhD"
- trigger: ";dhar"
  replace: "I Wayan Dharma Artana, MD, PAED, Consultant​"
- trigger: ";eka"
  replace: "Eka Gunawijaya, MD, PAED, Consultant​"
- trigger: ";ka"
  replace: "Ketut Ariawati, MD, PAED, Consultant​, PhD"
- trigger: ";san"
  replace: "I G.N. Sanjaya Putra, MD, PAED, Consultant​"
- trigger: ";dl"
  replace: "I Made Gede Dwi Lingga Utama, MD, PAED, Consultant​, PhD"
- trigger: ";nila"
  replace: "Gusti Ayu Putu Nilawati, MD, PAED, Consultant​, MARS"
- trigger: ";ds"
  replace: "Dewi Sutriani Mahalini, MD, PAED​, PhD"
- trigger: ";wid"
  replace: "A. A. N. K. P. Widnyana, , MD, PAED, Consultant​"
- trigger: ";juna"
  replace: "Putu Junara Putra, MD, PAED, Consultant​"
- trigger: ";dyah"
  replace: "Dyah Kanya Wati, MD, PAED, Consultant​, PhD"
- trigger: ";budi"
  replace: "I Nyoman Budi Hartawan, MD, M.Sc., PAED, Consultant​, PhD"
- trigger: ";ayu"
  replace: "I G. A. P. Eka Pratiwi, MD, M.Kes, PAED, Consultant​, PhD"
- trigger: ";sug"
  replace: "I G. A. N. Sugitha Adnyana, MD, PAED, Consultant​"
- trigger: ";gus"
  replace: "dr. I Wayan Gustawan, MD, M.Sc., PAED, Consultant​"
- trigger: ";rin"
  replace: "dr. Ayu Setyorini, MD, M. M., M.Sc., PAED, Consultant​"
- trigger: ";wit"
  replace: "Komang Ayu Witarini, MD, PAED, Consultant​"
- trigger: ";ven"
  replace: "Ni Putu Veny Kartika Yanti, MD, M.Sc.,PAED, Consultant​, PhD"
- trigger: ";met"
  replace: "Ni Nyoman Metriani Nesa, MD, M.Sc., PAED, Consultant​"
- trigger: ";suk"
  replace: "Made Sukmawati, MD, PAED, Consultant​"
- trigger: ";ram"
  replace: "Ida Bagus Ramajaya Sutawan, MD, M.Biomed, PAED, Consultant​"
- trigger: ";vina"
  replace: "Putu Mas Vina Paramitha, MD, M.Biomed, PAED"
- trigger: ";dy"
  replace: "I Made Darma Yuda, MD, M.Biomed, PAED"
- trigger: ";prat"
  replace: "Ni Luh Sukma Pratiwi Murti, MD, M.Biomed, PAED"
- trigger: ";krish"
  replace: "Bagus Ngurah Mahakrishna, MD, M.Biomed, PAED"
- trigger: ";yan"
  replace: "Kadek Ayu Yani Lastariana, MD, M.Biomed, PAED"
- trigger: ";apsa"
  replace: "Ni Luh Sri Apsari, MD, M.Biomed, PAED"
- trigger: ";upen"
  replace: "Wega Upendra Sindhughosa, MD, M.Biomed, PAED"
- trigger: ";yull"
  replace: "Made Yullyantara Saputra, MD, PAED"
- trigger: ";sis"
  replace: "Siska Permanasari Sinardja, MD, PAED"
- trigger: ";karm"
  replace: "I Made Karma Setiyawan, MD, PAED"